version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - db_data:/app/data
    restart: always
    environment:
      - DB_PATH=/app/data/observe.db
    # To run on free tier, limit memory
    deploy:
      resources:
        limits:
          memory: 500M

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # For local Docker testing. In AWS EC2, you would set this to your EC2 public IP or domain
        NEXT_PUBLIC_API_BASE_URL: "http://localhost:8000"
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 500M

volumes:
  db_data:
