export type UserRole =
  | 'PATIENT'
  | 'PHYSIOTHERAPIST'
  | 'ORTHOPEDIC_SURGEON'
  | 'CLINIC_ADMIN'
  | 'INSURANCE_AUDITOR';

export type Permission =
  | 'VIEW_OWN_TELEMETRY'
  | 'VIEW_PATIENT_COHORT'
  | 'EDIT_PRESCRIPTION'
  | 'SIGN_CLINICAL_NOTE'
  | 'EXPORT_RTM_BILLING'
  | 'MANAGE_CLINIC_USERS';

const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  PATIENT: ['VIEW_OWN_TELEMETRY'],
  PHYSIOTHERAPIST: ['VIEW_PATIENT_COHORT', 'EDIT_PRESCRIPTION', 'SIGN_CLINICAL_NOTE', 'VIEW_OWN_TELEMETRY'],
  ORTHOPEDIC_SURGEON: ['VIEW_PATIENT_COHORT', 'EDIT_PRESCRIPTION', 'SIGN_CLINICAL_NOTE', 'EXPORT_RTM_BILLING'],
  CLINIC_ADMIN: ['VIEW_PATIENT_COHORT', 'EXPORT_RTM_BILLING', 'MANAGE_CLINIC_USERS'],
  INSURANCE_AUDITOR: ['VIEW_PATIENT_COHORT', 'EXPORT_RTM_BILLING'],
};

export function hasPermission(role: UserRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}
